version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prisma-network

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/mydb?schema=public"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run dev"
    networks:
      - prisma-network

volumes:
  postgres_data:

networks:
  prisma-network:
    driver: bridge
